// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhRVKpCCKfgh2j26_lmidbF37xARPK5_w',
    appId: '1:523215420067:web:14134369f3fc2b78d65d16',
    messagingSenderId: '523215420067',
    projectId: 'grouseries',
    authDomain: 'grouseries.firebaseapp.com',
    storageBucket: 'grouseries.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp_CELGdMcLamLl_c1RsIFEh4qZX4OBpg',
    appId: '1:523215420067:android:5f9e8d06557f886cd65d16',
    messagingSenderId: '523215420067',
    projectId: 'grouseries',
    storageBucket: 'grouseries.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkgGJN4goBoCEfBFbqLjqQv-4GNy0OITo',
    appId: '1:523215420067:ios:f839c8f20712d726d65d16',
    messagingSenderId: '523215420067',
    projectId: 'grouseries',
    storageBucket: 'grouseries.firebasestorage.app',
    iosBundleId: 'com.example.grouseries',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkgGJN4goBoCEfBFbqLjqQv-4GNy0OITo',
    appId: '1:523215420067:ios:f839c8f20712d726d65d16',
    messagingSenderId: '523215420067',
    projectId: 'grouseries',
    storageBucket: 'grouseries.firebasestorage.app',
    androidClientId:
        '523215420067-2th4jq06e24auijvu8iv8ptfpld54uns.apps.googleusercontent.com',
    iosClientId:
        '523215420067-g51ai6o4sdupjbqvsfhmhmfu2g5lj3t8.apps.googleusercontent.com',
    iosBundleId: 'com.example.grouseries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhRVKpCCKfgh2j26_lmidbF37xARPK5_w',
    appId: '1:523215420067:web:c7f1b930b9de61fad65d16',
    messagingSenderId: '523215420067',
    projectId: 'grouseries',
    authDomain: 'grouseries.firebaseapp.com',
    storageBucket: 'grouseries.firebasestorage.app',
  );
}
